import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { css } from '../../styled-system/css';
import { MswProvider } from '../libs/msw/msw-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        // @keep-sorted-css
        className={css({
          position: 'relative',
          isolation: 'isolate',
        })}
      >
        <MswProvider>{children}</MswProvider>
      </body>
    </html>
  );
}
